---
- name: Set value for required hashes
  consul_kv:
    host: "{{host}}"
    key: config/general/required-hashes
    value: "sha256,sha512"

- name: Set value for load rate limit
  consul_kv:
    host: "{{host}}"
    key: config/fileloader/load-rate-limit
    value: "50"
