---
- name: Set value for required hashes
  consul_kv:

    key: config/general/required-hashes
    value: "SHA-256,SHA-512"

- name: Set value for load rate limit
  consul_kv:

    key: config/fileloader/load-rate-limit
    value: "50"

- name: Set value for thumbnail size
  consul_kv:

    key: config/general/thumbnail-size
    value: "300"

- name: Set value for integration database name
  consul_kv:

    key: config/mongodb/database/integration
    value: "mongodbintegration"

- name: Set value for production database name
  consul_kv:

    key: config/mongodb/database/si2
    value: "si2"

- name: Set vhost for SI2 on RabbitMQ
  consul_kv:
    key: config/rabbitmq/vhost
    value: "{{ rabbitmq_vhost }}"
