---
- name: Create Systemd unit for Consul
  template:
    src: systemd-unit.j2
    dest: /etc/systemd/system/consul.service    

- name: Enable and start Consul agent
  systemd:
    name: consul
    daemon_reload: yes
    state: started
    enabled: yes

