---
- fail: msg="Please set the gossip_encryption_key (preferably using vault)"
  when: gossip_encryption_key is undefined

- name: Install python Consul
  apt:
    cache_valid_time: "{{apt_cache_timeout}}"
    name: python3-consul
    state: present

- name: Create consul user
  user:
    name: consul
    system: yes
    home: /etc/consul.d/
    shell: /bin/false

- name: Create Consul configuration  directory
  file:
    state: directory
    path: /etc/consul.d/
    recurse: yes
    owner: consul
    group: consul

- name: Create Consul data directory
  file:
    state: directory
    path: /var/consul/
    recurse: yes
    owner: consul
    group: consul
    
- name: Copy Systemd unit for Consul
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service
  notify: Reload Consul

- name: Create consul main configuration
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
  notify: Restart Consul

- name: Create consul encryption configuration
  template:
    src: encrypt.hcl.j2
    dest: /etc/consul.d/encrypt.hcl
  notify: Restart Consul

- name: Enable and start Consul agent
  systemd:
    name: consul
    state: started
    enabled: yes

- name: Wait for consul agent to start up
  wait_for:
    timeout: 10
    host: "{{ consul_client_ip }}"
    port: 8500
