---
- name: Read Vault auth methods 
  uri:
    url: "{{ vault_api_url }}/sys/auth"
    method: GET
    headers:
      X-Vault-Token: "{{ vault_token }}"
  register: auth_response
  delay: 1
  retries: 10
  until: auth_response.status == 200
  # Retries are a workaround for Vault and / or Consul not being ready despite reporting as such

- name: Enable approle auth
  uri:
    url: "{{ vault_api_url }}/sys/auth/approle"
    method: POST
    body_format: json
    status_code: 204
    headers:
      X-Vault-Token: "{{ vault_token }}"
    body:
      type: approle
      config:
        default_lease_ttl: 10m
        max_lease_ttl: 30m
      
  register: approle_enable_response
  when: auth_response['json']['data']['approle/'] is not defined

- name: Create DBnode approle
  uri:
    url: "{{ vault_api_url }}/auth/approle/role/dbnode"
    method: POST
    body_format: json
    status_code: 204
    headers:
      X-Vault-Token: "{{ vault_token }}"
    body:
      token_ttl: 30m
      token_period: 30m
      token_policies:
        - node
