---
- name: Check if PKI secrets engine is enabled
  uri:
    url: "{{ vault_api_url }}/sys/mounts"
    headers:
      X-Vault-Token: "{{ vault_token }}"
  register: mounts_response

- name: Enable PKI secrets engine
  block:
    - name: Enable PKI secrets engine via API call
      uri:
        url: "{{ vault_api_url }}/sys/mounts/pki"
        method: POST
        body_format: json
        status_code: 204
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body:
          type: pki
          config:
            # TTL of 1 year
            max_lease_ttl: 8760h

  when: mounts_response['json']['data']['pki/'] is not defined

- name: Generate PKI CA
  uri:
    url: "{{ vault_api_url }}/pki/root/generate/internal"
    method: POST
    body_format: json
    body:
      common_name: "{{ ssl_domain }}"
      # TTL of 1 year
      ttl: 8760h
    headers:
      X-Vault-Token: "{{ vault_token }}"
    status_code:
      - 200
      - 204

- name: Create / Update rabbitmq PKI role
  uri:
    url: "{{ vault_api_url }}/pki/roles/rabbitmq"
    method: POST
    body_format: json
    body:
      allow_any_name: true
      enforce_hostnames: false
      allowed_domains:
        - "{{ ssl_domain }}"
      allow_subdomains: true
      ttl: 720h
    headers:
      X-Vault-Token: "{{ vault_token }}"
    status_code: 204

- name: Create / Update docker registry PKI role
  uri:
    url: "{{ vault_api_url }}/pki/roles/registry"
    method: POST
    body_format: json
    body:
      allow_any_name: true
      enforce_hostnames: false
      allowed_domains:
        - "{{ ssl_domain }}"
      allow_subdomains: true
      ttl: 720h
    headers:
      X-Vault-Token: "{{ vault_token }}"
    status_code: 204
