---
- name: Check if PKI secrets engine is enabled
  uri:
    url: "{{ vault_api_url }}/sys/mounts"
    headers:
      X-Vault-Token: "{{ vault_token }}"
  register: mounts_response

- name: Enable PKI secrets engine
  block:
    - name: Enable PKI secrets engine via API call
      uri:
        url: "{{ vault_api_url }}/sys/mounts/pki"
        method: POST
        body_format: json
        status_code: 204
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body:
          type: pki
          config:
            # TTL of 1 year
            max_lease_ttl: 8760h

  when: mounts_response['json']['data']['pki/'] is not defined
