---
- name: Remove exisitng binary
  when: force
  file:
    path: "{{ consul_binary }}"
    state: absent
  tags: packages

- name: Check that the Consul binary exists
  stat:
    path: "{{ consul_binary }}"
  register: consul_binary_stat
  tags: packages

- name: Download and install Consul binary
  block:
    - name: Install zip
      apt:
        cache_valid_time: "{{ apt_cache_timeout }}"
        name: zip

    - name: Create temporary file for Consul binary zip
      tempfile:
        state: file
        suffix: consul_binary
      register: temp_consul
  
    - name: Download Consul tarball
      get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: "{{ temp_consul.path }}"

    - name: Unpack Consul
      unarchive:
        src: "{{ temp_consul.path }}"
        remote_src: yes
        dest: /usr/local/bin/
        creates: "{{ consul_binary }}"
        owner: root

  when: not consul_binary_stat.stat.exists
  tags: packages
