---
- name: Remove exisitng binary
  when: force
  file:
    path: "{{ consul_binary }}"
    state: absent
  tags: package

- name: Check that the Consul binary exists
  stat:
    path: "{{ consul_binary }}"
  register: consul_binary_stat
  tags: package

- name: Download and install Consul binary
  block:
    - name: Install zip
      apt:
        name: zip
  
    - name: Download Consul tarball
      get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: "{{ consul_binary_download_directory }}"

    - name: Unpack Consul
      unarchive:
        src: "{{ consul_binary_download_directory }}/consul_{{ consul_version }}_linux_amd64.zip"
        remote_src: yes
        dest: /usr/local/bin/
        creates: "{{ consul_binary }}"
        owner: root

  when: not consul_binary_stat.stat.exists
  tags: package
