---
ansible_python_interpreter: "python3"
apt_cache_timeout: 86400

erlang_ssl_path: "/usr/lib/erlang/lib/ssl-8.2.3/ebin"
rabbitmq_config_dir: "/etc/rabbitmq"
rabbitmq_ssl_config: "{{ rabbitmq_config_dir }}/rabbitmq.conf"
ca_cert_path: "{{ rabbitmq_config_dir }}/ca_cert.pem"
server_cert_path: "{{ rabbitmq_config_dir }}/server_cert.pem"
server_key_path: "{{ rabbitmq_config_dir }}/server_key.pem"
client_cert_path: "{{ rabbitmq_config_dir }}/client_cert.pem"
client_key_path: "{{ rabbitmq_config_dir }}/client_key.pem"
