---
- name: Install docker package
  apt:
    name: docker.io
    state: present
  when: not nomad_server
  tags: package

# TODO replace this with secret from Vault
- name: Check that the Nomad gossip key is set
  assert:
    quiet: yes
    msg: Please set the gossip_encryption_key (preferably using vault)
    that:
      - gossip_encryption_key is defined

- name: Create Nomad configuration  directory
  file:
    state: directory
    path: "{{ nomad_config_directory }}"
    recurse: yes

- name: Create Nomad data directory
  file:
    state: directory
    path: "{{ nomad_data_directory }}"
    recurse: yes
    
- name: Create systemd unit for Nomad
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
  notify: Reload systemd daemon

- name: Create Nomad main configuration
  template:
    src: nomad.hcl.j2
    dest: "{{ nomad_config_directory }}/nomad.hcl"
  notify: Restart Nomad

- name: Enable and start Nomad agent
  systemd:
    name: nomad
    state: started
    enabled: yes
