---
- name: Check if dbnode approle exist
  uri:
    url: "{{ vault_api_url }}/auth/approle/role"
    method: LIST
    body_format: json
    status_code:
    - 200
    - 404
    headers:
      X-Vault-Token: "{{ vault_token }}"

  register: approle_list
  check_mode: no

- name: Setup dbnode dev approle
  block:
  - name: Create dbnode approle
    uri:
      url: "{{ vault_api_url }}/auth/approle/role/dbnode"
      method: POST
      body_format: json
      status_code: 204
      headers:
        X-Vault-Token: "{{ vault_token }}"
      body:
        token_ttl: 30m
        token_period: 30m
        token_policies: "dbnode"
  when: "'dbnode' not in approle_list['json']['data']['keys']"

- name: Rename dbnode approle role id
  uri:
    url: "{{ vault_api_url }}/auth/approle/role/dbnode/role-id"
    method: POST
    body_format: json
    status_code: 204
    headers:
      X-Vault-Token: "{{ vault_token }}"
    body:
      role_id: dbnode

- name: Lookup dbnode approle secret-id
  uri:
    url: "{{ vault_api_url }}/auth/approle/role/dbnode/secret-id/lookup"
    method: POST
    body_format: json
    status_code:
      - 200
      - 204
    headers:
      X-Vault-Token: "{{ vault_token }}"
    body:
      secret_id: dbnode
  register: dbnode_lookup

- name: Create custom dbnode approle secret id
  uri:
    url: "{{ vault_api_url }}/auth/approle/role/dbnode/custom-secret-id"
    method: POST
    body_format: json
    status_code: 200
    headers:
      X-Vault-Token: "{{ vault_token }}"
    body:
      secret_id: dbnode
  when: dbnode_lookup.status == 204
