---
- name: Reload Consul
  systemd:
    name: consul
    daemon_reload: yes
  notify: Restart Consul

- name: Restart Consul
  systemd:
    name: consul
    state: restarted

- name: Restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted

- name: Persist iptables
  command: netfilter-persistent save
