---
- name: Reaload Consul
  systemd:
    name: consul
    daemon_reload: yes
  notify: Restart Consul

- name: Restart Consul
  systemd:
    name: consul
    state: restarted
  notify: Wait for consul start up

- name: Wait for consul start up
  wait_for:
    delay: 2
    timeout: 10
    host: "{{ consul_client_ip }}"
    port: 8500
