---
- name: Erlang SSL lib must exist
  stat:
    path: "{{ erlang_ssl_path }}"
  register: erlang_ssl_path_stat

- name: Fail if the Erlang SSL library is not found
  fail:
    msg: "Erlang SSL path not found"
  when: not(erlang_ssl_path_stat.stat.isdir is defined and erlang_ssl_path_stat.stat.isdir)

- name: Create RabbitMQ SSL configuration
  template:
    src: ssl_dist.config.j2
    dest: /etc/rabbitmq/ssl_dist.config
    owner: rabbitmq
    group: rabbitmq

# TODO conditional restart, only if config files have changed
- name: Restart RabbitMQ server
  systemd:
    name: rabbitmq-server
    state: restarted

- name: Register RabbitMQ SSL service with consul
  consul:
    service_name: rabbitmq-ssl
    service_port: 5671
    tags: message-broker,rabbitmq
