---
- name: Create Vault user
  user:
    name: vault
    system: yes
    home: /etc/vault.d/
    shell: /bin/false

- name: Create Vault configuration  directory
  file:
    state: directory
    path: /etc/vault.d/
    recurse: yes
    owner: vault
    group: vault

- name: Copy Systemd unit for Vault
  copy:
    src: vault.service
    dest: /etc/systemd/system/vault.service
  notify:
    - Reload systemd daemon
    - Restart Vault service

- name: Create Vault main configuration
  template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
  notify: Restart Vault service

- name: Enable and start Vault agent
  systemd:
    name: vault
    state: started
    enabled: yes

# This is required as the Vault service needs to up and running to continue
- name: Flush handlers
  meta: flush_handlers

- name: Wait for Vault agent to start up
  wait_for:
    timeout: 10
    port: 8200
