---
- hosts: localhost

  roles:
    - consul-kv-config
    - docker-vault-init
    - vault-approle-auth
    - vault-policy
    - vault-pki
    - vault-kv
    #- dev-rabbitmq-credentials #TODO create RabbitMQ integration user via Vault?
    - rabbitmq-server
    - vault-rabbitmq-secrets
    - dev-vault-credentials
  vars:
    host: consul
    vault_server_address: vault
