---
- name: Install RabbitMQ server and ansible dependencies
  apt:
    cache_valid_time: "{{apt_cache_timeout}}"
    name: rabbitmq-server
  tags: package

- name: Fix RabbitMQ stop bug
  replace:
    path: /lib/systemd/system/rabbitmq-server.service
    regexp: "rabbitmqctl stop"
    replace: "rabbitmqctl shutdown"

  notify:
    - Reload systemd daemon
    - Restart RabbitMQ server

- name: Flush handlers
  meta: flush_handlers

- name: Enable and start RabbitMQ server
  systemd:
    name: rabbitmq-server
    enabled: yes
    state: started
