---
- name: Install RabbitMQ server and ansible dependencies
  apt:
    cache_valid_time: "{{apt_cache_timeout}}"
    name: rabbitmq-server
  tags: packages

- name: Fix RabbitMQ stop bug
  replace:
    path: /lib/systemd/system/rabbitmq-server.service
    regexp: "rabbitmqctl stop"
    replace: "rabbitmqctl shutdown"

- name: Enable and start RabbitMQ server
  systemd:
    daemon_reload: yes
    name: rabbitmq-server
    enabled: yes
    state: started