---
- name: Register RabbitMQ service with consul
  consul:
    service_name: rabbitmq
    service_port: 5672
    tags: message-broker,rabbitmq
    host: "{{ host }}"

- name: Check if RabbitMQ admin credentails exist in Vault
  uri:
    url: "{{ vault_api_url }}/kv/rabbitmq/admin"
    method: GET
    body_format: json
    status_code:
    - 200
    - 404
    headers:
      X-Vault-Token: "{{ vault_token }}"

  register: password_response
  check_mode: no

- name: Generate RabbitMQ admin credentials
  block:
  - name: Store RabbitMQ admin credentials
    uri:
      url: "{{ vault_api_url }}/kv/rabbitmq/admin"
      method: POST
      body_format: json
      status_code: 204
      headers:
        X-Vault-Token: "{{ vault_token }}"
      body:
        username: guest
        password: guest
    register: create_rabbitmq_creds

  when: password_response.status == 404

- name: Get RabbitMQ admin credentails from Vault
  uri:
    url: "{{ vault_api_url }}/kv/rabbitmq/admin"
    method: GET
    body_format: json
    status_code:
    - 200
    - 404
    headers:
      X-Vault-Token: "{{ vault_token }}"

  register: password_response
  check_mode: no

- name: Set queue name for file digest queue
  consul_kv:
    key: config/rabbitmq/queue/file-digest
    value: "file-digest"
    host: "{{ host }}"

- name: Set queue name for file resize queue
  consul_kv:
    key: config/rabbitmq/queue/file-resize
    value: "file-resize"
    host: "{{ host }}"

- name: Set queue name for thumbnails
  consul_kv:
    key: config/rabbitmq/queue/thumbnail
    value: "thumbnails"
    host: "{{ host }}"

- name: Set queue name for hash
  consul_kv:
    key: config/rabbitmq/queue/hash
    value: "hashes"
    host: "{{ host }}"

- name: Set queue name for thumbnail requests
  consul_kv:
    key: config/rabbitmq/queue/thumbnail-request
    value: "thumbnail-request"
    host: "{{ host }}"

- name: Set queue name for pre processed files
  consul_kv:
    key: config/rabbitmq/queue/file-pre-processed
    value: "file-pre-processed"
    host: "{{ host }}"

- name: Set vhost for SI2 on RabbitMQ
  consul_kv:
    key: config/rabbitmq/vhost
    value: "{{ rabbitmq_vhost }}"
    host: "{{ host }}"
