---
- name: Install RabbitMQ server and ansible dependencies
  apt:
    cache_valid_time: "{{apt_cache_timeout}}"
    name: rabbitmq-server

- name: Fix RabbitMQ stop bug
  replace:
    path: /lib/systemd/system/rabbitmq-server.service
    regexp: "rabbitmqctl stop"
    replace: "rabbitmqctl shutdown"

- name: Erlang SSL lib must exist
  stat:
    path: "{{ erlang_ssl_path }}"
  register: erlang_ssl_path_stat

- name: Fail if the Erlang SSL library is not found
  fail:
    msg: "Erlang SSL path not found"
  when: not(erlang_ssl_path_stat.stat.isdir is defined and erlang_ssl_path_stat.stat.isdir)

- name: Create RabbitMQ SSL configuration
  template:
    src: ssl_dist.config.j2
    dest: /etc/rabbitmq/ssl_dist.config
    owner: rabbitmq
    group: rabbitmq

- name: Enable and start RabbitMQ server
  systemd:
    daemon_reload: yes
    name: rabbitmq-server
    enabled: yes
    state: started    

- name: Register RabbitMQ service with consul
  consul:
    service_name: rabbitmq
    service_port: 5672
    tags: message-broker,rabbitmq

- name: Remove RabbitMQ guest user
  rabbitmq_user:
    name: guest
    state: absent

- name: Create RabbitMQ integration user
  rabbitmq_user:
    user: integration
    password: "{{integration_pwd}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
    state: present

- name: Create rabbitmq si2 user
  rabbitmq_user:
    user: si2
    password: "m6dtSqijKqldu6zHE9hK"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Enable rabbitmq management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
#TODO use prompt param for si2 password

- name: Store password for si2 user in consul
  consul_kv:
    key: config/rabbitmq/users/si2
    value: "{{si2_pwd}}"

- name: Set queue name for file digest queue
  consul_kv:
    key: config/rabbitmq/queue/file-digest
    value: "file-digest"

- name: Set queue name for file resize queue
  consul_kv:
    key: config/rabbitmq/queue/file-resize
    value: "file-resize"

- name: Set queue name for thumbnails
  consul_kv:
    key: config/rabbitmq/queue/thumbnail
    value: "thumbnails"

- name: Set queue name for hash
  consul_kv:
    key: config/rabbitmq/queue/hash
    value: "hashes"

- name: Set queue name for thumbnail requests
  consul_kv:
    key: config/rabbitmq/queue/thumbnail-request
    value: "thumbnail-request"

- name: Set queue name for pre processed files
  consul_kv:
    key: config/rabbitmq/queue/file-pre-processed
    value: "file-pre-processed"
    

