---
- name: Install RabbitMQ server and ansible dependencies
  import_tasks: install-rabbitmq-bintray-repo.yml
  tags: package

- name: Register RabbitMQ service with consul
  consul:
    service_name: rabbitmq
    service_port: 5672
    tags: message-broker,rabbitmq

- name: Remove RabbitMQ guest user
  rabbitmq_user:
    name: guest
    state: absent

- name: Check if RabbitMQ admin credentails exist in Vault
  uri:
    url: "{{ vault_api_url }}/kv/rabbitmq/admin"
    method: GET
    body_format: json
    status_code:
    - 200
    - 404
    headers:
      X-Vault-Token: "{{ vault_token }}"

  register: password_response
  check_mode: no

- name: Generate RabbitMQ admin credentials
  block:
  - set_fact:
      rabbitmq_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"

  - name: Store RabbitMQ admin credentials
    uri:
      url: "{{ vault_api_url }}/kv/rabbitmq/admin"
      method: POST
      body_format: json
      status_code: 204
      headers:
        X-Vault-Token: "{{ vault_token }}"
      body:
        username: admin
        password: "{{ rabbitmq_password }}"
    register: create_rabbitmq_creds

  when: password_response.status == 404

- name: Get RabbitMQ admin credentails from Vault
  uri:
    url: "{{ vault_api_url }}/kv/rabbitmq/admin"
    method: GET
    body_format: json
    status_code:
    - 200
    - 404
    headers:
      X-Vault-Token: "{{ vault_token }}"

  register: password_response
  check_mode: no

- name: Create RabbitMQ admin user
  rabbitmq_user:
    user: "{{ password_response.json.data.username }}"
    password: "{{ password_response.json.data.password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
    state: present

- name: Enable rabbitmq management and shovel plugin
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_shovel,rabbitmq_shovel_management
    state: enabled
    new_only: true

- name: Set queue name for file digest queue
  consul_kv:
    key: config/rabbitmq/queue/file-digest
    value: "file-digest"

- name: Set queue name for file resize queue
  consul_kv:
    key: config/rabbitmq/queue/file-resize
    value: "file-resize"

- name: Set queue name for thumbnails
  consul_kv:
    key: config/rabbitmq/queue/thumbnail
    value: "thumbnails"

- name: Set queue name for hash
  consul_kv:
    key: config/rabbitmq/queue/hash
    value: "hashes"

- name: Set queue name for thumbnail requests
  consul_kv:
    key: config/rabbitmq/queue/thumbnail-request
    value: "thumbnail-request"

- name: Set queue name for pre processed files
  consul_kv:
    key: config/rabbitmq/queue/file-pre-processed
    value: "file-pre-processed"
    

