---
- name: Check that the Nomad binary exists
  stat:
    path: "{{ nomad_binary }}"
  register: nomad_binary_stat
  tags: package

- name: Download and install Nomad binary
  block:
    - name: Install zip
      apt:
        name: zip
  
    - name: Download Nomad tarball
      get_url:
        url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        dest: "{{ nomad_binary_download_directory }}"

    - name: Unpack Nomad
      unarchive:
        src: "{{ nomad_binary_download_directory }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        remote_src: yes
        dest: /usr/local/bin/
        creates: "{{ nomad_binary }}"
        owner: root

  when: not nomad_binary_stat.stat.exists
  tags: package
