---
- name: Check that the Nomad binary exists
  stat:
    path: "{{ nomad_binary }}"
  register: nomad_binary_stat
  tags: package

- name: Download and install Nomad binary
  block:
    - name: Install zip
      apt:
        cache_valid_time: "{{ apt_cache_timeout }}"
        name: zip

    - name: Create temporary file for Nomad binary zip
      tempfile:
        state: file
        suffix: nomad_binary
      register: temp_nomad
  
    - name: Download Nomad tarball
      get_url:
        url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        dest: "{{ temp_nomad.path }}"

    - name: Unpack Nomad
      unarchive:
        src: "{{ temp_nomad.path }}"
        remote_src: yes
        dest: /usr/local/bin/
        creates: "{{ nomad_binary }}"
        owner: root

  when: not nomad_binary_stat.stat.exists
  tags: package
